[package]
name = "vanity-prefix"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["derive", "cargo"] }
sp-core = { version = "28.0.0" }
sp-runtime = { version = "31.0.1" }
